serial_number: cpr-j100-0001
version: 0

system: # These are system level configs
    self: A200-1
    hosts: # These are the hosts that are involved in this system
        self: A200-1
        platform: # The main computer for this system, ie the robot's computer
            A200-1: 192.168.131.1
        onboard: # These are additional on-board computers such as a secondary computer or software kit
            A200-B: 192.168.131.5
            ONAV-KIT: 192.168.131.10
        remote: # These are remote machines which need to interact with this system such as laptops or other robots
            CPR12345: 10.10.10.101
            USERS-PC: 10.10.10.1
    ros2:
        username: administrator
        namespace: a200_0001
        domain_id: 0
        rmw_implementation: rmw_fastrtps_cpp
        workspaces: []

platform: # These are are parameters specific to a a platform
    controller: ps4 # ps4 or logitech
    decorations: # Platform specific accessories
        front_bumper:
            extension: 0.1
            model: wibotic
            xyz: [0.0, 0.0, 0.0]
            rpy: [0.0, 0.0, 0.0]
        rear_bumper:
            extension: 0
            model: default
            xyz: [0.0, 0.0, 0.0]
            rpy: [0.0, 0.0, 0.0]
        top_plate:
            model: pacs
            xyz: [0.0, 0.0, 0.0]
            rpy: [0.0, 0.0, 0.0]
        structure:
            model: sensor_arch_510
            xyz: [0.0, 0.0, 0.0]
            rpy: [0.0, 0.0, 0.0]
    extras:
        urdf: None
        control: None

# Sensors: grouped by sensor types.
#  - model: unique model of that sensor type
#  - urdf_enabled: toggle to add model to description
#  - launch_enabled: toggle to add node to launch file
sensors:
    # List of Cameras
    camera:
      - model: flir_blackfly
        urdf_enabled: true
        launch_enabled: true
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        ros_parameters:
          connection_type: USB3
          encoding: BayerRG8
          fps: 30
          serial: 0
      - model: intel_realsense
        urdf_enabled: true
        launch_enabled: true
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        ros_parameters:
          serial_no: 12345
          device_type: d435
          enable_color: true
          rgb_camera:
            profile: "640,480,30"
          enable_depth: true
          depth_module:
            profile: "640,480,30"
          pointcloud:
            enable: true
          anything: true
    gps:
      - model: swiftnav_duro
        urdf_enabled: true
        launch_enabled: true
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        ros_parameters:
          ip_address: 192.168.131.30
          port: 55555
          gps_receiver_frame_id: duro
          imu_frame_id: duro
    lidar3d:
      - model: velodyne_lidar
        urdf_enabled: true
        launch_enabled: true
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        ros_parameters:
          device_ip: 192.168.131.20
          port: 2368
          model: VLP16
    lidar2d:
      - model: sick_lms1xx
        urdf_enabled: true
        launch_enabled: true
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        ros_parameters:
          hostname: 192.168.131.20
          port: 6000
          min_ang: -3.1415
          max_ang: 3.1415
      - model: hokuyo_ust10
        urdf_enabled: true
        launch_enabled: true
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        ros_parameters:
          ip_address: 192.168.131.21
          ip_port: 6000
          angle_max: -3.1415
          angle_min: 3.1415
    imu:
      - model: microstrain_imu
        urdf_enabled: true
        launch_enabled: true
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        ros_parameters:
          imu_frame_id: test_link
          port: /dev/test
          use_enu_frame: false
