version: 0
 
system: # These are system level configs
    self: J100-1
    hosts: # These are the hosts that are involved in this system
        platform: # The main computer for this system, ie the robot's computer
            J100-1: 192.168.131.1
        onboard: # These are additional on-board computers such as a secondary computer or software kit
            J100-B: 192.168.131.5
            ONAV-KIT: 192.168.131.10
        remote: # These are remote machines which need to interact with this system such as laptops or other robots
            CPR12345: 10.10.10.101
            USERS-PC: 10.10.10.1
    ros2:
        namespace: HOSTNAME
        domain_id: 123
        rmw_implementation: rmw_fastrtps_cpp

platform: # These are are parameters specific to a a platform
    serial_number: cpr-j100-0001
    decorations: # Platform specific accessories
        front_bumper:
            enable: true
            extension: 0.1
            model: wibotic
        rear_bumper:
            enable: true
            extension: 0.2
            model: default
        pacs:
            full_risers:
              - level: 1
                height: 0.5
              - level: 2
                height: 0.5
            row_risers:
              - row: 1
                level: 1
                height: 0.5
              - row: 2
                level: 1
                height: 0.5
            brackets:
              a01_bracket:
                  model: horizontal
                  extension: 0.0
                  parent: "A01"
                  xyz: [0.0, 0.0, 0.2]
                  rpy: [0.0, 0.0, 0.0]
              a02_bracket:
                  model: horizontal
                  extension: 0.0
                  parent: A02
                  xyz: [0.0, 0.0, 0.0]
                  rpy: [0.0, 0.0, 0.0]
    extras:
        urdf: /fake/path/empty.urdf.xacro
        control: /fake/path/empty.yaml


mounts:
    front_pivot:
        enabled: true
        parent_link: front_mount
        accessory_link: front_pivot_mount
        model: fath_pivot
        angle: 0
        xyz: [0, 0, 0]
        rpy: [0, 0, 0]
 
sensors: # Various sensors
    lidars:
        0:
            model: hokuyo_ust10 # model of the sensor
            driver: true # If the driver should be launched
            host: J100-1 # The host where the driver will launched on
            description: true # If the description is enabled
            parent_link: front_pivot_mount
            xyz: [0, 0, 0]
            rpy: [0, 0, 0]
            # Below are sensor specific params
            error_limit: 5
        1:
            model: sick-lms100
            driver: true
            host: J100-1B
            description: true
            parent_link: front_pivot_1
            xyz: [0, 0, 0]
            rpy: [0, 0, 0]
            error_limit: 5
    gps:
        0:
            model: nmea
            driver: true
            host: J100-1
            description: true
            parent_link: front_gps_mount
            xyz: [0, 0, 0]
            rpy: [0, 0, 0]
